# Generated by Django 3.2.4 on 2023-02-18 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20230218_1101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['user__first_name', 'user__last_name'], 'permissions': [('cancel_order', 'Can cancel order')]},
        ),
    ]
